sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Th4qcYFVOyxarLOu8EofVjvs8ORo78vbIReNgf8LJ/A6oQ1YPsfBn+KuYav6S9QnNpFlXLuqcQ3d0XIgghNVEFw7c2l/cpRe5dB/DjgYcUGBv1e4qs3nw0NSFL8ZGgoGnAmuPTq1kLARLXrJWgSedk88fd6j5IFzcWdzcj6aqefYzYFJ3LjFSOTzVZ2K2SVHxiLTv9RhLaHipMBDiK3KXP4UhfjR+MsTZx9FFzvi+BPFsReeU6mnkmwKTwrpXsv87HSq0UiWyMRN3WEeuunPxso+9116PS968EH4AWJLjrK/1MY216oAiUYNow7MyiuxxOtouv11s3LXodYhiKSnUVbovYtwrtMhifFxb/6H38Mvuc5k+Fsi0nzPV2PFhrsUBNjcBbjBvKhWIu2Fk3kDNPPwOxn+GySMlG9qAt9bjhzh5PAopUW9jjDzcOUDt/FtcoxnmjlPpWz8AarvgmVmuH9Mu3HNi3NH2W/qrzGvFVYecZv2eANkTwte7pqOPiHazGg1fyX0Z26JWtxHoy8ZU8uHESrN7LLPcBKwXeI1FcJV+AKXzzQPmraCk9yKxixrgbYY5Ym9LeDQJuodThCTQeIAYkqpXJb+fTIr7yR1bCUfVLokMPiY4gAwl5dIz+mgjff1lAm5vVxvyO6bPG2MXz941YRzuB2bQI6AZcpu6R0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/-Undo---A-Novel_480
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy